### ISSUE TITLE
Question: why to hook both SSL_CTX_set_custom_verify and x509TrustManager?

### ISSUE THREAD

**Issue by omer680** [Eltion/Tiktok-SSL-Pinning-Bypass#14]
Hello, 
why it's not enough to just create your custom x509TrustManager and perform your custom certificate validation in the checkClientTrusted, checkServerTrusted, getAcceptedIssuers? why you also hook the SSL_CTX_set_custom_verify? why do we need to hook both? i understand that SSL_CTX_set_custom_verify function is a method used to set a custom callback function to verify SSL certificates during the SSL/TLS handshaking process, so why i cant hook SSL_CTX_set_custom_verify and use the default x509TrustManager?

is it right to say that your custom x509TrustManager actually disabling certificate validation, and that's why any certificate wil be accepted, but will fail in the ssl pinning (for example, because the certificate public key is different from the hardcoded one), and that's why you also hook the SSL_CTX_set_custom_verify's callbacks and always return true.

Another question, how do you know that the app used the SSL_CTX_set_custom_verify function? 

Thanks!

**Comment by Eltion** [comment]
The main function which does the ssl pinning is the SSL_CTX_set_custom_verify, but only hooking that one will cause some of the of the requests to fail since some don't use it, as it shown in the picture below.
![image](https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/assets/18504798/f3995940-95c3-4ee7-928f-cac4315600a7)

For this reason I added the hooks for x509TrustManager
