### ISSUE TITLE
[Support x86] The client failed to negotiate a TLS connection

### ISSUE THREAD

**Issue by happeecoder** [Eltion/Tiktok-SSL-Pinning-Bypass#2]
I tried patched APK version tiktok-v26.0.2.apk and v25.9.4 on nox player(not rooted). No traffic interception. Please help

**Method**  
Patched APK 

**App info**
 - Version: tiktok-v26.0.2.apk
 - Arch: x86, x86_64, armeabi-v7a, arm64-v8a

**Device info**
- Model: Samsung SM-G977N, Nox Emulator
- Android Version: 9

**Proxy tool**
brup: v2022.8.4

**Logs**
Brup event log.

![tiktok-pinning](https://user-images.githubusercontent.com/69116151/190911106-09e9bbcd-dca7-4b59-96d6-56d2b1f46f06.png)

**Comment by Eltion** [comment]
@happeecoder  This the patch is only for `armeabi-v7a` and `arm64-v8a`. Nox player is `x86` so the patched apk will not work. 
Actually to bypass in x86 since Tiktok is only using  okhttp you can simply use this script [Universal Android SSL Pinning Bypass with Frida](https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/).

Here is an article that shows how to use that:
https://infosecwriteups.com/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29

**Comment by happeecoder** [comment]
can you suggest any android emulator which supports `arm64-v8a` or `armeabi-v7a` ?
Because I cant find TikTok x86 apk

**Comment by Eltion** [comment]
@happeecoder the tiktok apk is universal so it works on architecture including x86 so there is no specific apk for x86.

About the emulator using arm or arm64 this would be hard if your pc is not arm. I assume your using windows so probably not. You can try the official android emulator which has some arm system images but I doubt it will work.

**Comment by happeecoder** [comment]
> @happeecoder This the patch is only for `armeabi-v7a` and `arm64-v8a`. Nox player is `x86` so the patched apk will not work. Actually to bypass in x86 since Tiktok is only using okhttp you can simply use this script [Universal Android SSL Pinning Bypass with Frida](https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/).
> 
> Here is an article that shows how to use that: https://infosecwriteups.com/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29

As you suggested I tried universal-ssl-pinning-bypass.

![tiktok-pinning_frida](https://user-images.githubusercontent.com/69116151/191445561-a90010f6-fb45-4e86-bbe0-d7b2402c3332.png)

Burp shooting request but no response

![tiktok-pinning_burp](https://user-images.githubusercontent.com/69116151/191445389-340e9d70-82a1-4ea5-9c3d-1adabf5d53e4.png)

Do you know why ?.
Does anyone has a solution

Thanks in advance

**Comment by Eltion** [comment]
@happeecoder it seems like I was actually wrong there is x86 build for the new versions of tiktok. The reason why it's opening on Nox Emulator is because they use ARM translation to run arm instructions.

I was able to create a patched apk which is working on Nox Emulator x86.

https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/releases/download/v26.3.2/tiktok-v26.3.2-x86-arm-translation.apk

![image](https://user-images.githubusercontent.com/18504798/192051323-1507319c-61ec-4d31-b4ae-9f329a7aad8f.png)
